### ISSUE TITLE
Support new PA districts 

### ISSUE THREAD

**Issue by ben-pr-p** [unitedstates/districts#11]
PA has new districts!

There are GeoJSON files here (https://github.com/R35I5T/dev/blob/master/PA.geojson) which come from the state website (http://www.pacourts.us/news-and-statistics/cases-of-public-interest/league-of-women-voters-et-al-v-the-commonwealth-of-pennsylvania-et-al-159-mm-2017?66). They look right to me.

I'll attempt format them and make a PR later today

**Comment by JoshData** [comment]
fyi, It would probably be incorrect to use the new district boundaries in connection with legislator data elsewhere in this github organization until the next Congress after this year's elections begins on January 3, 2019.

**Comment by konklone** [comment]
Our `cds/` directory is year-indexed: https://github.com/unitedstates/districts/tree/gh-pages/cds

Maybe it's time to start a `2018/` or `2020/` directory?
