### ISSUE TITLE
Several states are out of date

### ISSUE THREAD

**Issue by smach** [unitedstates/districts#5]
FYI there has been redistricting in at least two states since 2012, you may want to update those files. [Florida and Virginia changed their Congressional Districts maps for 2016](http://www.dailykos.com/story/2016/1/12/1465389/-An-interactive-look-at-the-new-2016-Florida-and-Virginia-congressional-maps-and-their-stats), while it looks like [North Carolina](https://ballotpedia.org/Redistricting_in_North_Carolina) will redistrict after the 2016 elections.

**Comment by dwillis** [comment]
We've got a pull request that covers this; all three states have changed district boundaries.

**Comment by smach** [comment]
Whoops sorry never mind
